### ISSUE TITLE
Can't open my swagger.json

### ISSUE THREAD

**Issue by darrenhaken** [Rebilly/ReDoc#125]
I tried using the following template to open a Swagger doc:

```
<!DOCTYPE html>
<html>
<head>
    <title>API Docs</title>
    <!-- needed for mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<!--<redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>-->
<redoc spec-url="https://companydomain.com/swagger.json"></redoc>
<script src="https://rebilly.github.io/ReDoc/releases/v1.2.0/redoc.min.js"></script>
</body>
</html>
```

If I open the Petstore sample it works but my JSON file eventually times out and fails. There are no error messages to help me debug exactly why it's not working. Any clues?

**Comment by darrenhaken** [comment]
I suspect the issue is that I'm trying to add a spec using HTTPS but the fetch command isn't using the protocol.

The Swagger JSON I'm trying to query isn't available on HTTP.

**Comment by IvanGoncharov** [comment]
@darrenhaken Can you please copy browser console or make a screenshot?
I suspect that you have a problem with CORS since you file served under `companydomain.com`.
To confirm this you can use, this service: https://crossorigin.me/

**Comment by darrenhaken** [comment]
@IvanGoncharov So I prepended the https://crossorigin.me/ and the resource was retrieved in the network tab so it does appear likely its a CORS issue.

However after doing that I get the following error:

![image](https://cloud.githubusercontent.com/assets/953467/19372613/6f3a3328-9172-11e6-872a-9363c9ea6e23.png)

**Comment by RomanGotsiy** [comment]
@darrenhaken seems like you don't have `version` field which in your `info` object which is required according to [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#info-object).

**Comment by darrenhaken** [comment]
@RomanGotsiy that seemed to be the issue and it's resolved now thanks!

One last thing about the ReDoc UI; is there a way of adding auth headers when testing out the service?

**Comment by RomanGotsiy** [comment]
@darrenhaken if you need to document authentication headers you should probably use [securityDefinitions](http://swagger.io/specification/#securityDefinitionsObject).
They are still not rendered by ReDoc but this will be implemented soon. Check out issue: https://github.com/Rebilly/ReDoc/issues/7

I'm closing this issue
