### ISSUE TITLE
Response description is not rendered as Markdown.

### ISSUE THREAD

**Issue by Jean-Daniel** [Rebilly/ReDoc#158]
While using swagger-ui, responses description are properly rendered when they contains Markdown tags.

Using ReDoc, responses description are dumped as raw text and not properly formatted.

**Comment by RomanGotsiy** [comment]
Fixed, will be available in the next release

**Comment by RomanGotsiy** [comment]
@Jean-Daniel new version `1.6.2` with the fix has been just released

**Comment by Jean-Daniel** [comment]
Nope. Didn't fix the issue.
Isn't there an extra pipe in the fix commit ( '|| marked' instead of '| marked') ?

**Comment by RomanGotsiy** [comment]
@Jean-Daniel yes, you're right.
My fault. Will fix for the next release.
